# GCP container-scanner service account
# Create with: gcloud iam service-accounts create container-scanner-sa

apiVersion: iam.cnpg.io/v1beta1
kind: ServiceAccount
metadata:
  name: container-scanner-sa

---
# Cloud Run invoker role for Cloud Scheduler
apiVersion: iam.cnpg.io/v1beta1
kind: IAMBinding
metadata:
  name: container-scanner-run-invoker
roleRef:
  kind: ClusterRole
  apiGroup: iam.cnpg.io
  name: cloud-run-invoker
subjects:
- kind: ServiceAccount
  name: container-scanner-sa

---
# Service account permissions for Container Analysis API access
# Artifact Registry Reader
apiVersion: iam.cnpg.io/v1beta1
kind: IAMBinding
metadata:
  name: container-scanner-artifact-registry
roleRef:
  apiGroup: iam.cnpg.io
  kind: ClusterRole
  name: artifactregistry.reader
subjects:
- kind: ServiceAccount
  name: container-scanner-sa

---
# Container Analysis Reader
apiVersion: iam.cnpg.io/v1beta1
kind: IAMBinding
metadata:
  name: container-scanner-analysis
roleRef:
  apiGroup: iam.cnpg.io
  kind: ClusterRole
  name: containeranalysis.viewer
subjects:
- kind: ServiceAccount
  name: container-scanner-sa
